enum ROUTE_NAMES {
  PROMOTION = 'Promotion List',
  PROMOTION_PARENT = 'PROMOTION_PARENT',
  PROMOTION_DETAIL = 'PROMOTION_DETAIL',
  OPERATOR_PROMOTION = 'OPERATOR_PROMOTION',
  PROMOTION_TEMPLATE = 'Promotion Template',
  DELETE_PROMOTION = 'DELETE_PROMOTION',
  EDIT_PROMOTION = 'EDIT_PROMOTION',
  DELETE_PROMOTION_TEMPLATE = 'DELETE_PROMOTION_TEMPLATE',
  CREATE_PROMOTION = 'CREATE_PROMOTION',
  CREATE_INITAL_PROMOTION_SETTING = 'CREATE_INITAL_PROMOTION_SETTING',
  CREATE_INITAL_TEMPLATE_PROMOTION_SETTING = 'CREATE_INITAL_TEMPLATE_PROMOTION_SETTING',
  CREATE_CRITERIA = 'CREATE_CRITERIA',
  CREATE_REWARD_PRODUCT_SETUP = 'CREATE_REWARD_PRODUCT_SETUP',
  CREATE_ADDITIONAL_CRITERIA = 'CREATE_ADDITIONAL_CRITERIA',
  CREATE_ADDITIONAL_CRITERIA_STEP_2 = 'CREATE_ADDITIONAL_CRITERIA_STEP_2',
  CREATE_PROMOTION_SUMMARY = 'CREATE_PROMOTION_SUMMARY',
  LIST_ACCOUNT_PAYABLE = 'LIST_ACCOUNT_PAYABLE',
  ACCOUNT_PAYABLE_DETAIL = 'ACCOUNT_PAYABLE_DETAIL',
  DISTRIBUTOR_DISCOUNT = 'DISTRIBUTOR_DISCOUNT',
  CREATE_DISTRIBUTOR_DISCOUNT = 'CREATE_DISTRIBUTOR_DISCOUNT',
  DELETE_DISTRIBUTOR_DISCOUNT = 'DELETE_DISTRIBUTOR_DISCOUNT',
  EDIT_DISTRIBUTOR_DISCOUNT = 'EDIT_DISTRIBUTOR_DISCOUNT',
  PROMOTION_APPROVAL = 'PROMOTION_APPROVAL',
  DETAIL_PROMOTION_APPROVAL = 'DETAIL_PROMOTION_APPROVAL',

  // CNDN
  LIST_CNDN = 'LIST_CNDN',
  CREATE_CNDN = 'CREATE_CNDN',
  DETAIL_CNDN = 'DETAIL_CNDN',
  PRINT_CNDN = 'PRINT_CNDN',
  UPDATE_CNDN = 'UPDATE_CNDN',

  // DISCOUNT
  DISCOUNT = 'DISCOUNT',

  CREATE_INITIAL_DISCOUNT = 'CREATE_INITIAL_DISCOUNT',
  CREATE_DISCOUNT_CRITERIA = 'CREATE_DISCOUNT_CRITERIA',
  CREATE_DISCOUNT_SUMMARY = 'CREATE_DISCOUNT_SUMMARY',

  EDIT_INITIAL_DISCOUNT = 'EDIT_INITIAL_DISCOUNT',
  EDIT_DISCOUNT_CRITERIA = 'EDIT_DISCOUNT_CRITERIA',
  EDIT_DISCOUNT_SUMMARY = 'EDIT_DISCOUNT_SUMMARY',
  DETAIL_DISCOUNT = 'DETAIL_DISCOUNT',

  EDIT_DISCOUNT = 'EDIT_DISCOUNT',

  DELETE_DISCOUNT = 'DELETE_DISCOUNT',

  // MANAGE RETURN
  MANAGE_RETURN_PARENT = 'MANAGE_RETURN_PARENT',
  MANAGE_RETURN = 'MANAGE_RETURN',
  CREATE_MANAGE_RETURN = 'CREATE_MANAGE_RETURN',
  DETAIL_MANAGE_RETURN = 'DETAIL_MANAGE_RETURN',

  // RETURN APPROVAL
  RETURN_APPROVAL = 'RETURN_APPROVAL',
  DETAIL_RETURN_APPROVAL = 'DETAIL_RETURN_APPROVAL',

  // SUPPLIER INVOICE RETURN
  SUPPLIER_INVOICE_RETURN = 'SUPPLIER_INVOICE_RETURN',
  CREATE_SUPPLIER_INVOICE_RETURN = 'CREATE_SUPPLIER_INVOICE_RETURN',
  EDIT_SUPPLIER_INVOICE_RETURN = 'EDIT_SUPPLIER_INVOICE_RETURN',
  DETAIL_SUPPLIER_INVOICE_RETURN = 'DETAIL_SUPPLIER_INVOICE_RETURN',

  // REPORT
  RETURN_REPORT = 'RETURN_REPORT',
  DETAIL_RETURN_REPORT = 'DETAIL_RETURN_REPORT',

  //GAMIFICATION
  MANAGE_GAMIFICATION = 'MANAGE_GAMIFICATION',
  CREATE_GAMIFICATION = 'CREATE_GAMIFICATION',
  DETAIL_GAMIFICATION = 'DETAIL_GAMIFICATION',
  EDIT_GAMIFICATION = 'EDIT_GAMIFICATION',

  // AP PAYMENT
  LIST_AP_PAYMENT = 'LIST_AP_PAYMENT',
  DETAIL_AP_PAYMENT = 'DETAIL_AP_PAYMENT',
  CREATE_AP_PAYMENT = 'CREATE_AP_PAYMENT',

  // INCENTIVE GROUP
  INCENTIVE_GROUP = 'INCENTIVE_GROUP',

  // SHIPMENT
  SHIPMENT = 'Shipment',
  PARENT_SHIPMENT = 'parent shipment',

  // SHIPEMNT LIST
  SHIPMENT_LIST = 'Shipment List',

  // SHIPMENT REPORT
  SHIPMENT_REPORT = 'SHIPMENT_REPORT',

  // SHIPMENT PICK LIST
  PICK_LIST = 'PICK_LIST',

  // STOCK OPNAME
  STOCK_OPNAME = 'STOCK_OPNAME',
  CREATE_STOCK_OPNAME_FIRST_STEP = 'CREATE_STOCK_OPNAME_FIRST_STEP',
  CREATE_STOCK_OPNAME_SECOND_STEP = 'CREATE_STOCK_OPNAME_SECOND_STEP',
}

export default ROUTE_NAMES;
